import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Cloud, Coffee, Flame, Leaf, Mountain, Star } from "lucide-react";
import BookingBar from "@/components/BookingBar";
import CTASection from "@/components/CTASection";
import ExperienceCard from "@/components/ExperienceCard";
import JournalCard from "@/components/JournalCard";
import Reveal from "@/components/Reveal";
import SectionHeading from "@/components/SectionHeading";
import StayCard from "@/components/StayCard";
import { experiences, galleryImages, images, journalPosts, offers, stays } from "@/lib/amara-data";

const testimonials = [
  { quote: "There is a particular hour when the valley disappears into cloud and the fire is lit. We have travelled widely, but we have never felt stillness arranged so beautifully.", name: "Elena & Marc", place: "Singapore" },
  { quote: "Our children remember the pine trail and cacao by the hearth. We remember how the team anticipated every detail without ever making the stay feel managed.", name: "The Villanueva family", place: "Manila" },
  { quote: "Amara understands that privacy is not isolation. The hosts appeared exactly when needed, then left us alone with the view. An exceptionally thoughtful retreat.", name: "Sophie R.", place: "London" },
];

export default function Home() {
  return <>
    <section className="paper-grain relative flex min-h-screen items-end overflow-hidden bg-pine-black px-5 pb-24 pt-36 text-white lg:px-10 lg:pb-20">
      <Image src={images.hero} alt="Amara Ridge villas above a mist-filled Philippine highland valley" fill priority className="hero-breathe object-cover" sizes="100vw" />
      <div className="absolute inset-0 bg-gradient-to-r from-pine-black/75 via-pine-black/20 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-pine-black/65 via-transparent to-pine-black/30" />
      <div className="relative mx-auto w-full max-w-[94rem]"><Reveal><p className="eyebrow text-ember">Cordillera · Philippines</p><h1 className="mt-6 max-w-6xl text-balance font-display text-[clamp(4.2rem,10vw,10rem)] leading-[.78] tracking-[-.02em]">Above the clouds, life moves differently.</h1><p className="mt-7 max-w-xl text-sm leading-7 text-white/72 sm:text-base">A private mountain sanctuary of six villas, considered Filipino hospitality and the beautiful luxury of having nowhere else to be.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/booking" className="inline-flex items-center justify-center gap-3 bg-ember px-7 py-4 text-[10px] font-bold uppercase tracking-[.18em] text-pine-black hover:bg-white">Book your escape <ArrowUpRight className="h-4 w-4" /></Link><Link href="/stays" className="inline-flex items-center justify-center gap-3 border border-white/40 px-7 py-4 text-[10px] font-bold uppercase tracking-[.18em] hover:bg-white hover:text-pine-black">Explore villas</Link></div></Reveal></div>
      <a href="#story" aria-label="Discover more" className="gentle-drift absolute bottom-7 right-7 hidden items-center gap-2 text-[9px] uppercase tracking-[.2em] text-white/55 lg:flex">Discover <ArrowDown className="h-4 w-4" /></a>
    </section>

    <div className="bg-deep-forest px-4 pb-3 sm:px-6 lg:px-10"><BookingBar floating /></div>
    <div className="bg-deep-forest px-5 pb-12 pt-8 text-white lg:px-10"><div className="mx-auto grid max-w-[90rem] grid-cols-2 gap-y-7 border-t border-white/10 pt-8 text-center sm:grid-cols-4"><div><p className="font-display text-3xl text-ember">6</p><p className="mt-1 text-[8px] uppercase tracking-[.18em] text-white/45">Private villas</p></div><div><p className="font-display text-3xl text-ember">1:1</p><p className="mt-1 text-[8px] uppercase tracking-[.18em] text-white/45">Personal concierge</p></div><div><p className="font-display text-3xl text-ember">100%</p><p className="mt-1 text-[8px] uppercase tracking-[.18em] text-white/45">Philippine highland story</p></div><div><p className="font-display text-3xl text-ember">Always</p><p className="mt-1 text-[8px] uppercase tracking-[.18em] text-white/45">Breakfast included</p></div></div></div>

    <section id="story" className="bg-cloud px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto grid max-w-[90rem] items-center gap-14 lg:grid-cols-[.9fr_1.1fr]">
      <Reveal><div className="relative"><div className="relative aspect-[4/5] overflow-hidden"><Image src={images.villa} alt="Private Amara Ridge villa among Benguet pines" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 48vw" /></div><div className="absolute -bottom-8 -right-2 max-w-[15rem] bg-ember p-6 sm:right-[-2rem]"><Mountain className="h-7 w-7 stroke-[1.3]"/><p className="mt-4 font-display text-2xl leading-tight">Six private stays. One extraordinary ridge.</p></div></div></Reveal>
      <div className="lg:pl-12"><SectionHeading eyebrow="The Amara story" title="A gentler expression of the Philippine highlands." subtitle="Amara Ridge was imagined as a conversation between landscape and hospitality—deeply private, quietly modern and unmistakably Filipino." align="left" /><Reveal delay={.15}><div className="mt-9 grid gap-6 border-t border-pine-black/15 pt-8 sm:grid-cols-2"><p className="text-sm leading-7 text-pine-black/65">Built along the contours of a Cordillera ridge, every villa turns toward cloud, pine and changing light. Local stone holds the warmth of each hearth; broad eaves invite the rain to be watched, not avoided.</p><p className="text-sm leading-7 text-pine-black/65">Our hosts remember how you take your coffee, arrange days around your energy, and understand that sometimes the finest service is simply protecting your quiet.</p></div><Link href="/about" className="mt-8 inline-flex items-center gap-2 border-b border-pine-black pb-1 text-[10px] font-bold uppercase tracking-[.18em]">Our philosophy <ArrowUpRight className="h-4 w-4" /></Link></Reveal></div>
    </div></section>

    <section className="bg-linen/55 px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="Private stays" title="Your own place in the mountains." subtitle="Each villa has its own relationship with the ridge—forest, fire, water or the wide-open horizon." /><div className="mt-14 grid gap-6 md:grid-cols-2 lg:gap-8">{stays.slice(0,4).map((stay, index) => <Reveal key={stay.slug} delay={(index%2)*.1}><StayCard stay={stay}/></Reveal>)}</div><div className="mt-10 text-center"><Link href="/stays" className="inline-flex items-center gap-3 border border-pine-black px-7 py-4 text-[10px] font-bold uppercase tracking-[.18em] hover:bg-pine-black hover:text-white">View all stays <ArrowUpRight className="h-4 w-4" /></Link></div></div></section>

    <section className="bg-deep-forest px-5 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="The rhythm of Amara" title="Days shaped by curiosity, not schedules." subtitle="Move through pine forest, meet the people and ingredients of the highlands, or let an afternoon pass beside warm water." light /><div className="mt-14 grid gap-7 md:grid-cols-3">{experiences.slice(0,3).map((item, index)=><Reveal key={item.slug} delay={index*.08}><div className="[&_article>div:last-child]:border-white/15 [&_article>div:last-child_p]:text-white/60"><ExperienceCard item={item}/></div></Reveal>)}</div><div className="mt-10 text-center"><Link href="/experiences" className="inline-flex items-center gap-3 border border-white/30 px-7 py-4 text-[10px] font-bold uppercase tracking-[.18em] hover:bg-white hover:text-pine-black">Discover every experience <ArrowUpRight className="h-4 w-4" /></Link></div></div></section>

    <section className="grid bg-cloud lg:grid-cols-2"><div className="relative min-h-[70vh]"><Image src={images.wellness} alt="Open-air wellness pavilion in the Philippine highlands" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></div><div className="flex items-center px-5 py-20 lg:px-[10%]"><Reveal><p className="eyebrow text-clay">Wellness, naturally</p><h2 className="mt-6 font-display text-5xl leading-[.94] sm:text-7xl">The mountain does half the work.</h2><p className="mt-6 text-sm leading-7 text-pine-black/62">Cool air. Long sleep. A warm plunge in moving mist. Our wellness practice draws from Filipino hilot, local botanicals and the simple intelligence of being outdoors.</p><div className="mt-8 grid grid-cols-2 gap-5 border-y border-pine-black/15 py-7 text-[10px] font-bold uppercase tracking-[.14em]"><span className="flex items-center gap-2"><Leaf className="h-4 w-4 text-moss"/>Botanical rituals</span><span className="flex items-center gap-2"><Cloud className="h-4 w-4 text-moss"/>Forest bathing</span><span className="flex items-center gap-2"><Flame className="h-4 w-4 text-moss"/>Warm plunge</span><span className="flex items-center gap-2"><Coffee className="h-4 w-4 text-moss"/>Sleep infusions</span></div><Link href="/wellness" className="mt-8 inline-flex items-center gap-2 border-b border-pine-black pb-1 text-[10px] font-bold uppercase tracking-[.18em]">Restore at Amara <ArrowUpRight className="h-4 w-4"/></Link></Reveal></div></section>

    <section className="bg-soft-white px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="The table" title="Philippine ingredients, seen from a higher place." subtitle="At Sulo, the highlands arrive through fire, fermentation, native herbs, small farms and recipes held in living memory."/><div className="mt-14 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[34rem] overflow-hidden"><Image src={images.dining} alt="Filipino highland tasting menu at Sulo" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 65vw"/></div><div className="flex flex-col justify-between bg-ember p-8 sm:p-10"><div><p className="eyebrow text-pine-black">Sulo restaurant</p><h3 className="mt-6 font-display text-5xl leading-none">Rooted here. Served with a wider view.</h3><p className="mt-6 text-sm leading-7 text-pine-black/65">Breakfast follows the weather. Dinner follows the harvest. The tasting menu is Filipino in instinct and contemporary in its sense of restraint.</p></div><Link href="/dining" className="mt-10 inline-flex items-center gap-2 self-start border-b border-pine-black pb-1 text-[10px] font-bold uppercase tracking-[.18em]">Meet Sulo <ArrowUpRight className="h-4 w-4"/></Link></div></div></div></section>

    <section className="bg-cloud px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="Field of view" title="A place that changes by the hour."/><div className="mt-14 grid auto-rows-[220px] gap-3 sm:grid-cols-2 lg:grid-cols-4 lg:auto-rows-[260px]">{galleryImages.slice(0,6).map((item,index)=><Link href="/gallery" key={`${item.alt}-${index}`} className={`group relative overflow-hidden ${index===0||index===5?"sm:col-span-2":""}`}><Image src={item.src} alt={item.alt} fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 25vw"/><span className="absolute inset-0 bg-pine-black/0 transition group-hover:bg-pine-black/20"/></Link>)}</div><div className="mt-8 text-center"><Link href="/gallery" className="inline-flex items-center gap-2 border-b border-pine-black pb-1 text-[10px] font-bold uppercase tracking-[.18em]">Open the gallery <ArrowUpRight className="h-4 w-4"/></Link></div></div></section>

    <section className="bg-linen px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="Guest reflections" title="Carried home from the ridge."/><div className="mt-14 grid gap-5 lg:grid-cols-3">{testimonials.map((item,index)=><Reveal key={item.name} delay={index*.08}><blockquote className="h-full bg-soft-white p-8 sm:p-10"><div className="flex gap-1 text-ember">{Array.from({length:5}).map((_,i)=><Star key={i} className="h-3.5 w-3.5 fill-current"/>)}</div><p className="mt-8 font-display text-2xl leading-snug">“{item.quote}”</p><footer className="mt-9 border-t border-pine-black/10 pt-5 text-[9px] font-bold uppercase tracking-[.17em] text-pine-black/55">{item.name} · {item.place}</footer></blockquote></Reveal>)}</div></div></section>

    <section className="bg-deep-forest px-5 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="Curated stays" title="Arrive with less to arrange." subtitle="Four considered ways to experience the ridge, each flexible enough to feel entirely your own." light/><div className="mt-14 grid gap-px bg-white/15 md:grid-cols-2 lg:grid-cols-4">{offers.map((offer,index)=><article key={offer.slug} className="flex flex-col bg-deep-forest p-7"><p className="text-[9px] font-bold tracking-[.18em] text-ember">0{index+1} · {offer.length}</p><h3 className="mt-6 font-display text-3xl">{offer.name}</h3><p className="mt-4 flex-1 text-sm leading-7 text-white/55">{offer.description}</p><Link href={`/booking?offer=${offer.slug}`} className="mt-7 inline-flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.16em] text-ember">Request this stay <ArrowUpRight className="h-4 w-4"/></Link></article>)}</div><div className="mt-9 text-center"><Link href="/offers" className="inline-flex items-center gap-2 border-b border-white pb-1 text-[10px] font-bold uppercase tracking-[.18em]">View all offers <ArrowUpRight className="h-4 w-4"/></Link></div></div></section>

    <section className="bg-soft-white px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[94rem]"><SectionHeading eyebrow="From the journal" title="Notes from a slower altitude."/><div className="mt-14 grid gap-10 md:grid-cols-2">{journalPosts.slice(0,2).map(post=><JournalCard key={post.slug} post={post}/>)}</div></div></section>
    <CTASection />
  </>;
}
